name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish DotnetToolsCli
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PACKAGE_NAME: DotnetToolsCli
          PROJECT_FILE_PATH: App/App.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}